---

- name: Configure server with node exporter
  hosts: all
  become: True
  tasks:
  - name: Install node-exporter
    ansible.builtin.script: scripts/installNodeExporter.sh
    args:
      creates: /usr/local/bin/node_exporter