---

- name: Configure server with Letsencrypt certificate
  hosts: all
  become: True
  tasks:
  - name: Install Certificate
    ansible.builtin.script: scripts/installCertificate.sh {{ tls_domain }} {{ tls_email }}
    args:
      creates: /etc/letsencrypt/archive/letsenc/cert1.pem

  - name: copy tls default nginx config file
    copy: src=conf/nginx/default-w-tls.conf dest=/etc/nginx/sites-available/default

  - name: restart nginx
    service: name=nginx state=restarted