global:
    scrape_interval: 5s
scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 15s
      static_configs:
        - targets: ["localhost:9090"]
    - job_name: "node_exporter"
      static_configs:
        - targets: [ "es-monitor-01:9100", "es-access-01:9100", "es-ingress-01:9100", "es-master-01:9100" ]